# Generated by Django 3.2.25 on 2025-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('checkins', models.PositiveIntegerField(default=0)),
                ('home_district', models.CharField(blank=True, max_length=120)),
                ('attack_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('defend_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-score', 'username'],
            },
        ),
    ]
