# Generated by Django 3.2.25 on 2025-10-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_known_location',
            field=models.JSONField(blank=True, default=None, help_text='Last confirmed location payload from the client (lng/lat, district metadata, timestamp).', null=True),
        ),
    ]
