# Generated by Django 3.2.25 on 2025-10-16 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_player_last_known_location'),
    ]

def create_missing_users(apps, schema_editor):
    Player = apps.get_model('game', 'Player')
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    UserModel = apps.get_model(user_app_label, user_model_name)
    for player in Player.objects.filter(user__isnull=True):
        password = UserModel.objects.make_random_password()
        user = UserModel.objects.create_user(username=player.username, password=password)
        player.user = user
        player.save(update_fields=['user'])


def noop_reverse(apps, schema_editor):
    # Retain existing users; rolling back only removes the FK field.
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_player_last_known_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_missing_users, noop_reverse),
    ]
