# Generated by Django 3.2.25 on 2025-10-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='attack_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='checkin_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='defend_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='home_district_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='player',
            name='home_district_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
