# Generated by Django 3.2.25 on 2025-10-25 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20251018_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reverse_friend_links', to='game.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_links', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='friendlink',
            constraint=models.UniqueConstraint(fields=('player', 'friend'), name='unique_friend_link'),
        ),
        migrations.AddConstraint(
            model_name='friendlink',
            constraint=models.CheckConstraint(check=models.Q(('player', django.db.models.expressions.F('friend')), _negated=True), name='prevent_self_friendship'),
        ),
    ]
