# Generated by Django 3.2.25 on 2025-10-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20251025_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cooldown_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='player',
            name='cooldowns',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
