# Generated by Django 3.2.25 on 2025-10-29 22:11

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion
import django.db.models.expressions


def populate_district_points(apps, schema_editor):
    CheckIn = apps.get_model('game', 'CheckIn')
    CheckIn.objects.filter(action='attack').update(
        district_points_delta=-F('points_awarded'),
        party_multiplier_snapshot=1,
        party_size_snapshot=1,
    )
    CheckIn.objects.filter(action='defend').update(
        district_points_delta=F('points_awarded'),
        party_multiplier_snapshot=1,
        party_size_snapshot=1,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_district_engagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_parties', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='checkin',
            name='district_points_delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='is_party_contribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkin',
            name='party_multiplier_snapshot',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='checkin',
            name='party_size_snapshot',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(populate_district_points, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PlayerPartyBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_checkins', models.PositiveIntegerField(default=0)),
                ('shared_attack_points', models.PositiveIntegerField(default=0)),
                ('shared_contribution_points', models.PositiveIntegerField(default=0)),
                ('last_shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_party_bonds', to='game.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_bonds', to='game.player')),
            ],
            options={
                'ordering': ['-shared_checkins', 'partner__username'],
            },
        ),
        migrations.CreateModel(
            name='PartyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='game.party')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_memberships', to='game.player')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_party_invitations', to='game.player')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='game.party')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_party_invitations', to='game.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictContributionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=64)),
                ('contribution_points', models.PositiveIntegerField(default=0)),
                ('contribution_checkins', models.PositiveIntegerField(default=0)),
                ('last_contribution_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_contributions', to='game.player')),
            ],
            options={
                'ordering': ['-contribution_points'],
            },
        ),
        migrations.AddConstraint(
            model_name='playerpartybond',
            constraint=models.UniqueConstraint(fields=('player', 'partner'), name='unique_party_bond'),
        ),
        migrations.AddConstraint(
            model_name='playerpartybond',
            constraint=models.CheckConstraint(check=models.Q(('player', django.db.models.expressions.F('partner')), _negated=True), name='prevent_self_party_bond'),
        ),
        migrations.AddConstraint(
            model_name='partymembership',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True)), fields=('player',), name='unique_active_party_membership'),
        ),
        migrations.AddConstraint(
            model_name='partyinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('party', 'to_player'), name='unique_pending_party_invite'),
        ),
        migrations.AddConstraint(
            model_name='districtcontributionstat',
            constraint=models.UniqueConstraint(fields=('district_code', 'supporter'), name='unique_district_supporter_stat'),
        ),
    ]
