# Generated by Django 3.2.25 on 2025-11-02

import json
from pathlib import Path

from django.db import migrations, models


DISTRICT_CODE_FIELDS = (
    "kod_mc",
    "KOD_MC",
    "kod_uzohmp",
    "KOD_UZOHMP",
    "objectid",
    "OBJECTID",
)

DISTRICT_NAME_FIELDS = (
    "nazev_mc",
    "NAZEV_MC",
    "nazev_1",
    "NAZEV_1",
    "naz_uzohmp",
    "NAZ_UZOHMP",
    "name",
    "NAME",
    "nazev",
    "NAZEV",
)


def _resolve_catalog_path():
    base = Path(__file__).resolve().parents[3]
    candidate = base / "data" / "prague-districts.geojson"
    return candidate if candidate.exists() else None


def load_district_catalog(apps, schema_editor):
    District = apps.get_model("game", "District")
    path = _resolve_catalog_path()
    if path is None:
        return
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return

    features = payload.get("features") or []
    seen_codes = set()
    for feature in features:
        props = feature.get("properties") or {}
        code = None
        if feature.get("id") is not None:
            text = str(feature["id"]).strip()
            if text:
                code = text
        if not code:
            for field in DISTRICT_CODE_FIELDS:
                value = props.get(field)
                if value is None:
                    continue
                text = str(value).strip()
                if text:
                    code = text
                    break
        if not code or code in seen_codes:
            continue
        name = None
        for field in DISTRICT_NAME_FIELDS:
            value = props.get(field)
            if isinstance(value, str) and value.strip():
                name = value.strip()
                break
        if not name:
            name = f"District {code}"
        District.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "is_active": True,
            },
        )
        seen_codes.add(code)

    if seen_codes:
        District.objects.exclude(code__in=seen_codes).update(is_active=False)


def unload_district_catalog(apps, schema_editor):
    District = apps.get_model("game", "District")
    District.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_auto_20251029_2211"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "code"],
            },
        ),
        migrations.RunPython(load_district_catalog, unload_district_catalog),
    ]
