# Generated by Django 3.2.25 on 2025-11-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_district_strength_and_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='attacked_points_total',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative attack points dealt against this district.'),
        ),
        migrations.AddField(
            model_name='district',
            name='checkin_total',
            field=models.PositiveIntegerField(default=0, help_text='Total number of check-ins recorded for this district.'),
        ),
        migrations.AddField(
            model_name='district',
            name='current_strength',
            field=models.IntegerField(default=0, help_text='Live strength score after applying all attack and defend activity.'),
        ),
        migrations.AddField(
            model_name='district',
            name='defended_points_total',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative defend points contributed to this district.'),
        ),
        migrations.AddField(
            model_name='district',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerdistrictcontribution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
