# Generated by Django 3.2.25 on 2025-11-02 17:24

from django.db import migrations
from django.db.models import Case, Count, F, Sum, When, Max
from django.db.models.functions import Coalesce


def populate_district_activity(apps, schema_editor):
    District = apps.get_model("game", "District")
    CheckIn = apps.get_model("game", "CheckIn")

    aggregates = (
        CheckIn.objects.exclude(district_code__isnull=True)
        .exclude(district_code__exact="")
        .values("district_code")
        .annotate(
            defended=Coalesce(
                Sum(
                    Case(
                        When(action="defend", then=F("district_points_delta")),
                        default=0,
                    )
                ),
                0,
            ),
            attacked=Coalesce(
                Sum(
                    Case(
                        When(action="attack", then=-F("district_points_delta")),
                        default=0,
                    )
                ),
                0,
            ),
            checkins=Count("id"),
            last_activity=Max("occurred_at"),
            name_hint=Max("district_name"),
        )
    )

    processed_codes = set()
    for row in aggregates:
        code = (row.get("district_code") or "").strip()
        if not code:
            continue
        processed_codes.add(code)
        defended = int(row.get("defended") or 0)
        attacked = int(row.get("attacked") or 0)
        checkins = int(row.get("checkins") or 0)
        last_activity = row.get("last_activity")
        name = (row.get("name_hint") or "").strip()

        district, created = District.objects.get_or_create(
            code=code,
            defaults={
                "name": name or f"District {code}",
                "is_active": True,
            },
        )
        # Ensure newly created districts start from their base strength
        if created and district.current_strength == 0 and district.base_strength:
            district.current_strength = district.base_strength
            district.save(update_fields=["current_strength", "updated_at"])

        strength = district.base_strength + defended - attacked
        updates = {
            "defended_points_total": defended,
            "attacked_points_total": attacked,
            "checkin_total": checkins,
            "current_strength": strength,
        }
        if last_activity:
            updates["last_activity_at"] = last_activity
        if name and not district.name:
            updates["name"] = name
        District.objects.filter(pk=district.pk).update(**updates)

    # Districts with no historical check-ins should reset to their base strength
    reset_queryset = District.objects.all()
    if processed_codes:
        reset_queryset = reset_queryset.exclude(code__in=processed_codes)
    reset_queryset.update(
        defended_points_total=0,
        attacked_points_total=0,
        checkin_total=0,
        current_strength=F("base_strength"),
        last_activity_at=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20251102_1723'),
    ]

    operations = [
        migrations.RunPython(populate_district_activity, migrations.RunPython.noop),
    ]
