# Generated by Django 3.2.25 on 2025-11-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_populate_district_activity_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
