# Generated by Django 3.2.25 on 2025-11-30 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_player_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='district_ip_address',
            field=models.CharField(blank=True, default='', help_text='Synthetic IP derived from home district code to support cyber mechanics.', max_length=32),
        ),
        migrations.CreateModel(
            name='DistrictDdosEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_ip', models.CharField(blank=True, default='', max_length=32)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddos_attacks', to='game.player')),
                ('attacker_home_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_ddos_entries', to='game.district')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_ddos_entries', to='game.district')),
            ],
        ),
        migrations.AddIndex(
            model_name='districtddosentry',
            index=models.Index(fields=['district', 'expires_at'], name='game_distri_distric_2d1a00_idx'),
        ),
        migrations.AddIndex(
            model_name='districtddosentry',
            index=models.Index(fields=['attacker', 'expires_at'], name='game_distri_attacke_e2cecf_idx'),
        ),
    ]
