# Generated by Django 3.2.25 on 2025-12-01 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20251130_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='game.district')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to='game.player')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='districtchatmessage',
            index=models.Index(fields=['district', '-sent_at'], name='district_chat_time_idx'),
        ),
        migrations.AddIndex(
            model_name='districtchatmessage',
            index=models.Index(fields=['district', 'id'], name='district_chat_id_idx'),
        ),
    ]
