# Generated by Django 3.2.25 on 2025-12-?? ??:?? (manual)
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0027_merge_20251202_0001"),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictWormEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attacker_ip", models.CharField(blank=True, default="", max_length=32)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attacker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worm_attacks",
                        to="game.player",
                    ),
                ),
                (
                    "attacker_home_district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_worm_entries",
                        to="game.district",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_worm_entries",
                        to="game.district",
                    ),
                ),
                (
                    "ended_by_player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ended_worm_entries",
                        to="game.player",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="districtwormentry",
            index=models.Index(fields=["district", "expires_at"], name="game_distri_distric_c0bc86_idx"),
        ),
        migrations.AddIndex(
            model_name="districtwormentry",
            index=models.Index(fields=["attacker", "expires_at"], name="game_distri_attacke_93f42b_idx"),
        ),
    ]

