# Generated by Django 3.2.25 on 2026-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_player_profile_image_text'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='districtwormentry',
            name='game_distri_distric_c0bc86_idx',
        ),
        migrations.RemoveIndex(
            model_name='districtwormentry',
            name='game_distri_attacke_93f42b_idx',
        ),
        migrations.AddIndex(
            model_name='districtwormentry',
            index=models.Index(fields=['district', 'expires_at'], name='game_distri_distric_0de357_idx'),
        ),
        migrations.AddIndex(
            model_name='districtwormentry',
            index=models.Index(fields=['attacker', 'expires_at'], name='game_distri_attacke_8bd72c_idx'),
        ),
    ]
