# Generated by Django 3.2.25 on 2026-05-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_auto_20260118_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='two_factor_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
